# Generated by Django 3.2.13 on 2023-05-23 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='videos',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.JSONField(default=list, null=True),
        ),
        migrations.DeleteModel(
            name='Video',
        ),
    ]
